apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unscripted-living-postgres-backup-pvc
  namespace: unscripted-living
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
