# Generated by Django 6.0.4 on 2026-04-24 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_auto_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_gallery',
            field=models.BooleanField(default=False, help_text='Display posts as a photo gallery grid'),
        ),
    ]
